name: Bug report
about: Create a report to help us improve
title: "[Bug]: "
labels: 'status: ready to reproduce, type: bug'
assignees: ByungJun25
issue_body: true
inputs:
- type: dropdown
  attributes:
    label: Which project is related?
    required: true
    choices:
      - spring-security-instant
      - spring-security-instant-demo
      - spring-security-user-instant
      - spring-security-user-instant-demo

- type: textarea
  attributes:
    label: Describe the bug.
    required: true
    placeholder: "A clear and concise description of what the bug is."

- type: textarea
  attributes:
    label: To Reproduce
    required: true
    placeholder: "Add any other context about the problem here."
    value: "Steps to reproduce the behavior:
    1. Go to '...'
    2. Click on '....'
    3. Scroll down to '....'
    4. See error"

- type: textarea
  attributes:
    label: Expected behavior
    required: false
    placeholder: "A clear and concise description of what you expected to happen."

- type: textarea
  attributes:
    label: Screenshots
    required: false
    placeholder: "If applicable, add screenshots to help explain your problem."

- type: multi_select
  attributes:
    label: OS
    required: true
    description: Where does this bug appear
    choices:
      - Window
      - Linux
      - Mac
      - Docker
      - Others

- type: textarea
  attributes:
    label: Additional context
    required: false
    placeholder: Add any other context about the problem here.
