spring:
  application:
    name: spring-security-user-instant-demo
  config:
    activate:
      on-profile:
      - default
  datasource: 
    platform: h2
    hikari:
      jdbc-url: jdbc:h2:mem:instant
      username: test
      password: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  ## THYMELEAF DEFAULT SETTING
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

instant:
  security:
    permission:
      ignore-paths:
        ## ignore paths per HttpMethods
        GET:
          - /h2-consle
          - /h2-console/**
          - /console/**
          - /css/**
          - /js/**
          - /img/**
        POST:
          - /h2-consle
          - /h2-console/**
          - /console/**
      permission-urls:
        '[/admin]':
          '[*]':
            - ROLE_ADMIN
        '[/admin/**]':
          '[*]':
            - ROLE_ADMIN
        '[/user]':
          '[*]':
            - ROLE_USER
        '[/user/**]':
          '[*]':
            - ROLE_USER
      all:
        '[*]':
          - /
      anonymous:
        '[*]':
          - /anonymous
    login:
      page: /login
      successUrl: /mypage # default - '/'
      authenticationFailureUrl: /login?error
      usernameParameter: email # default - 'username'
      remember-me:
        enabled: true
        type: PERSISTENT
        token-validity-seconds: 86400
    logout:
      invalidateHttpSession: true
      clearAuthentication: true
      url: /logout
      successUrl: /login?logout
      deleteCookies:
        - JSESSIONID
    sessionManagement:
      creationPolicy: IF_REQUIRED
    authenticationEntryPoint:
      redirectUrl: /login?error
    accessDeniedHandler:
      redirectUrl: /error/accessDenied
    csrf:
      disabled: false
      cookieCsrfToken: false
    cors:
      '[/api/*]':
        allowedOrigins:
          - http://localhost:8080
        allowedHeaders:
          - x-requested-with
          - content-type
        allowedMethods:
          - HEAD
          - OPTIONS
          - GET
          - POST
          - PUT
        allowCredentials: true

server:
  port: 8080
  shutdown: graceful
  servlet:
    session:
      timeout: 60s ## for testing


