# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Spring Instant [Issue] CI with Maven

on:
  push:
    branches:
      - "!main"
  pull_request:
    branches:
      - "!main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: echo Issue branch action start
        run: echo Issue branch action start

      - name: checkout main code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and Test with Maven
        run: mvn -B package -PDev --file pom.xml
