# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Create pre-release

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'prefix for pre-release (ie. rc)'
        required: true
        default: 'rc'
      version:
        description: 'version for pre-release (ie. 1.0.0)'
        required: true
        default: '0.0.1'

jobs:
  create-prerelease:
    name: Create Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: echo create prerelease job start
        run: echo create prerelease job start

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Create Prerelease
        id: create_prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.prefix }}${{ github.event.inputs.version }}
          release_name: 🚀 Pre-Release ${{ github.event.inputs.prefix }}${{ github.event.inputs.version }}
          body: |
            🚀 Pre-Release ${{ github.event.inputs.prefix }}${{ github.event.inputs.version }} version from ${{ github.ref }}
          draft: false
          prerelease: true

  build-deploy:
    needs: create-prerelease
    name: deploy GitHub Maven Package
    runs-on: ubuntu-latest

    steps:
      - name: echo build and deploy job start
        run: echo build and deploy job start

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode -Drevision=${{ github.event.inputs.version }} -PRC deploy 
        env:
          GITHUB_TOKEN: ${{ github.token }}