# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Spring Instant [Tag - Release Candidate] Maven package

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'rc*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-prerelease:
    name: Create Prerelease
    runs-on: ubuntu-latest
    steps:
      - name: echo create prerelease job start
        run: echo create prerelease job start

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Prerelease
        id: create_prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Prerelease ${{ github.ref }}
          body: |
            Prerelease ${{ github.ref }}
          draft: false
          prerelease: true

  build-deploy:
    name: deploy GitHub Maven Package
    runs-on: ubuntu-latest

    steps:
      - name: echo build and deploy job start
        run: echo build and deploy job start

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode deploy -PRC
        env:
          GITHUB_TOKEN: ${{ github.token }}